# Generated by Django 6.1.2 on 2026-10-07 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('booking_status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('movie', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='bookings.movie')),
                ('seat', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatnum', to='bookings.seat')),
            ],
        ),
    ]
