# Generated by Django 6.1.2 on 2026-10-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_movie_description_alter_movie_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
    ]
