# Generated by Django 6.1.2 on 2026-10-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_alter_seat_booking_status"),
    ]

    operations = []
