# Generated by Django 6.1.2 on 2026-10-08 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_seat_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='bookings.movie'),
        ),
    ]
