# Generated by Django 6.1.2 on 2026-10-08 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='booking_status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seatnum', to='bookings.seat'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('movie', 'seat'), name='unique_movie_seat_booking'),
        ),
    ]
