# Generated by Django 6.1.2 on 2026-10-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_seat_booking_status_alter_booking_seat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
    ]
