# Generated by Django 6.1.2 on 2026-10-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_movie_seat_unique_booking'),
        ('bookings', '0006_seat_booking_status'),
    ]

    operations = [
    ]
