# Generated by Django 6.1.2 on 2026-10-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_merge_20261008_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
    ]
